### ISSUE TITLE
roszczenie odkupienia klawiatury

### ISSUE THREAD

**Issue by Aleks-1123** [sadordev/Zine-v2#1]
jak zobaczylem ten kod to zarzygalem klawiature, prosze mi ja odkupic.

**Comment by Fiberek** [comment]
Sąd Rejonowy dla m. st. Warszawy
Marszałkowska 82
Otwarte ⋅ Zamknięcie: 15:30

**Comment by sterzidev** [comment]
Tak wygląda Sąd do którego musi się pan udać: https://bip.warszawa.so.gov.pl/uploads/files/so-warszawa/dane-podstawowe/mstwarszawa/sr--m.-st.-Warszawy.png

**Comment by Aleks-1123** [comment]
dopsze mogem liszyc na odrzkodowanie?

**Comment by sterzidev** [comment]
Niestety to już musi być uzgodnione z wielkim developerem, pracownikiem nasa **A. Z. Fiut. Mr. Dyr. Sadordev** po boku wielkiego zbawiciela nasalang, moceklang - Mikołaj " Mondonno " Mocek.

**Comment by sterzidev** [comment]
``

**Comment by Aleks-1123** [comment]
LAMO SADOR CLOSUJE

**Comment by sterzidev** [comment]
ja ci zamkne guwniarzu

**Comment by sadordev** [comment]
> ja ci zamkne guwniarzu

zaraz ci dam gowniarzu

**Comment by sadordev** [comment]
> ja ci zamkne guwniarzu

to ze kod to gowno to nie znaczy ze ja jestem gowniarzem
